#!/bin/bash
# -Dpython.install_env=/home/colivier/mambaforge/envs/ubuntu 
DEBUG_FLAGS=""
# PREFIX="/usr/local"
PREFIX="/home/colivier/mambaforge/envs/ubuntu"
DEBUG_FLAGS="--debug -Doptimization=0"
meson setup -Dlibav=enabled ${DEBUG_FLAGS} --reconfigure -Dgpl=enabled --prefix=${PREFIX} $@ builddir
